FROM nvcr.io/nvidia/jax:23.10-py3

RUN python3 -m pip install --upgrade pip

RUN pip install absl_py==2.0.0
RUN pip install brax==0.10.3
RUN pip install cycler==0.12.1
RUN pip install etils==0.5.1
RUN pip install flax==0.7.4
RUN pip install matplotlib==3.8.3
RUN pip install mediapy==1.2.0
RUN pip install mujoco==3.1.3
RUN pip install mujoco_mjx==3.1.3
RUN pip install numpy==1.26.1
RUN pip install optax==0.1.7
RUN pip install setuptools==59.6.0
