FROM nvcr.io/nvidia/jax:23.10-py3

RUN python3 -m pip install --upgrade pip

RUN pip install absl_py
RUN pip install brax
RUN pip install cycler
RUN pip install etils
RUN pip install flax
RUN pip install matplotlib
RUN pip install mediapy
RUN pip install mujoco
RUN pip install mujoco_mjx
RUN pip install numpy
RUN pip install optax
RUN pip install setuptools